import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./tailwind.css";
import "./globals.css";
import { cn } from "../lib/utils";
import { NextProvider, ThemeProvider } from "./providers";
import "react-image-crop/dist/ReactCrop.css";
import getUser from "./actions/getUser";
import Navbar from "@/components/nav/Navbar";
import AppNavBar from "@/components/nav/AppNavBar";
import { ModalProvider } from "@/components/providers/ModalProvider";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
export const metadata: Metadata = {
  title: "Wavify",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();

  return (
    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background antialiased debug-screens flex flex-col"
        )}
      >
        <NextProvider>
          <ReactQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              storageKey="wavify-theme"
            >
              {!user ? (
                <>
                  <header className=" bg-background fixed top-0 w-full z-50 min-h-[100h]">
                    <Navbar></Navbar>
                  </header>
                  <main className="bg-background_content relative z-1 top-0 left-0 w-[100%] min-h-[100vh] py-[10vh]">
                    {children}
                  </main>
                  {/*<footer className=" bg-background fixed bottom-0 w-full z-50 min-h-[10vh]">
                  <Footer></Footer>
            </footer>*/}
                </>
              ) : (
                <>
                  <ModalProvider user={user} />
                  <header className=" bg-background w-full  min-h-[20h]">
                    <AppNavBar user={user}></AppNavBar>
                  </header>
                  <main className="bg-background_content relative z-1 top-0 left-0 w-[100%] flex-grow flex">
                    {children}
                  </main>
                  {/*<footer className=" bg-background fixed bottom-0 w-full z-50 min-h-[10vh]">
                  <Footer></Footer>
            </footer>*/}
                </>
              )}
            </ThemeProvider>
          </ReactQueryProvider>
        </NextProvider>
      </body>
    </html>
  );
}
